/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import  koneksi.koneksi;
import Frame.MenuUtama;

/**
 *
 * 
 */

public class Halaman_Mahasiswa extends javax.swing.JFrame {
private DefaultTableModel model;



public void clear(){
TFNAMA.setText("");
tfNPM.setText("");
TFSEMESTER.setText("");
TFROLE.setText("");
TFTAHUN.setText("");

}
public void  mahasiswa(){
model = new DefaultTableModel ();
             tabel_mhs.setModel(model);
             model.addColumn("NPM");
             model.addColumn("Nama");
             model.addColumn("Tahun Ajaran");
             model.addColumn("Semester");
             model.addColumn("Role");
             
             isitabel();
}


public void isitabel( ){
    
     model.getDataVector( ).removeAllElements( );
     model.fireTableDataChanged( );

     try{
          
           Statement st = (Statement) koneksi.konn(). createStatement( );
           String sql   = "Select * from mahasiswa";
           ResultSet res   = st.executeQuery(sql);

           
           while(res.next ()){
                Object[ ] obj = new Object[6];
                obj[0] = res.getString("npm");
                obj[1] = res.getString("nama");
                obj[2] = res.getString("thn_ajaran");
                obj[3] = res.getString("semester");
                obj[4] = res.getString("role");
                

                model.addRow(obj);
            }
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }
}





    public Halaman_Mahasiswa() {
        initComponents();
        mahasiswa();
        
        
             
    }
    

     
            
 
             
             
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_mhs = new javax.swing.JTable();
        tfNPM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFNAMA = new javax.swing.JTextField();
        TFTAHUN = new javax.swing.JTextField();
        TFSEMESTER = new javax.swing.JTextField();
        TFROLE = new javax.swing.JTextField();
        bttambah = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btUBAH = new javax.swing.JButton();
        btBersihkan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 400));

        tabel_mhs.setBackground(new java.awt.Color(255, 255, 255));
        tabel_mhs.setForeground(new java.awt.Color(51, 51, 51));
        tabel_mhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_mhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_mhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_mhs);

        tfNPM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfNPM.setForeground(new java.awt.Color(0, 0, 0));
        tfNPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNPMActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NPM");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NAMA");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("TAHUN");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ROLE");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("SEMESTER");

        TFNAMA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TFNAMA.setForeground(new java.awt.Color(0, 0, 0));
        TFNAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNAMAActionPerformed(evt);
            }
        });

        TFTAHUN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TFTAHUN.setForeground(new java.awt.Color(0, 0, 0));
        TFTAHUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTAHUNActionPerformed(evt);
            }
        });

        TFSEMESTER.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TFSEMESTER.setForeground(new java.awt.Color(0, 0, 0));
        TFSEMESTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSEMESTERActionPerformed(evt);
            }
        });

        TFROLE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TFROLE.setForeground(new java.awt.Color(0, 0, 0));
        TFROLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFROLEActionPerformed(evt);
            }
        });

        bttambah.setBackground(new java.awt.Color(102, 255, 51));
        bttambah.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        bttambah.setForeground(new java.awt.Color(0, 0, 0));
        bttambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_save_35px_4.png"))); // NOI18N
        bttambah.setText("ADD");
        bttambah.setBorder(null);
        bttambah.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });

        bthapus.setBackground(new java.awt.Color(255, 0, 51));
        bthapus.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        bthapus.setForeground(new java.awt.Color(0, 0, 0));
        bthapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_delete_35px.png"))); // NOI18N
        bthapus.setText("DELETE");
        bthapus.setBorder(null);
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        btUBAH.setBackground(new java.awt.Color(255, 153, 51));
        btUBAH.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btUBAH.setForeground(new java.awt.Color(0, 0, 0));
        btUBAH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_edit_file_35px.png"))); // NOI18N
        btUBAH.setText("EDIT");
        btUBAH.setBorder(null);
        btUBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUBAHActionPerformed(evt);
            }
        });

        btBersihkan.setBackground(new java.awt.Color(255, 255, 255));
        btBersihkan.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btBersihkan.setForeground(new java.awt.Color(0, 0, 0));
        btBersihkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_eraser_35px.png"))); // NOI18N
        btBersihkan.setText("CLEAR");
        btBersihkan.setBorder(null);
        btBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBersihkanActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_close_window_35px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MAHASISWA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFSEMESTER, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFROLE, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TFNAMA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfNPM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(62, 62, 62)
                            .addComponent(TFTAHUN, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bttambah, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btUBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btUBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttambah, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNPM, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFTAHUN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFSEMESTER, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFROLE, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNPMActionPerformed

    private void TFNAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNAMAActionPerformed

    private void TFTAHUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTAHUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTAHUNActionPerformed

    private void TFSEMESTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSEMESTERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFSEMESTERActionPerformed

    private void TFROLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFROLEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFROLEActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
       try {
           if(tfNPM.getText().equals("")){
            JOptionPane.showMessageDialog(null, " TIDAK BOLEH KOSONG");
        } else if (TFNAMA.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }
        else if (TFTAHUN.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }else if (TFSEMESTER.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }else if (TFROLE.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }
        else {
            String sql = "INSERT INTO mahasiswa VALUES ('"+tfNPM.getText()+"','"+TFNAMA.getText()+"','"+TFTAHUN.getText()+"','"+TFSEMESTER.getText()+"','"+TFROLE.getText()+"')";
            java.sql.Connection conn=(Connection)koneksi.konn();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan");
            isitabel();
            clear();
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_bttambahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btUBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUBAHActionPerformed
try{
            koneksi.konn();
             Statement st = (Statement) koneksi.konn(). createStatement( );
            String SQL = "update mahasiswa SET npm = '"+tfNPM.getText()+"', nama = '"+TFNAMA.getText()+"', thn_ajaran = '"
             +TFTAHUN.getText()+"', semester = '"+TFSEMESTER.getText()+"', role = '"+TFROLE.getText()+"' WHERE npm = '"+tfNPM.getText()+"'";
            st.executeUpdate(SQL);
            isitabel();
             clear();
            JOptionPane.showMessageDialog(null, "berhasil edit");
           
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }        
    }//GEN-LAST:event_btUBAHActionPerformed

    private void tabel_mhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_mhsMouseClicked
try {
            koneksi.konn();
            int row =tabel_mhs.getSelectedRow();
            String tabel_klik=(tabel_mhs.getModel().getValueAt(row, 0).toString());
            java.sql.Statement stm = koneksi.konn() .createStatement();
            java.sql.ResultSet sql = stm.executeQuery("select * from mahasiswa where npm='"+tabel_klik+"'");
            if(sql.next()){
                String id = sql.getString("npm");
                tfNPM.setText(id);
                String nama = sql.getString("nama");
                TFNAMA.setText(nama);
                String thn_ajaran = sql.getString("thn_ajaran");
                TFTAHUN.setText(thn_ajaran);
                String semester = sql.getString("semester");
                TFSEMESTER.setText(semester);
                String role = sql.getString("role");
                TFROLE.setText(role);
            }
        } catch (Exception e) {}       
    }//GEN-LAST:event_tabel_mhsMouseClicked

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
       try{
           koneksi.konn();
          Statement  st = koneksi.konn().createStatement();
            String SQL = "DELETE FROM mahasiswa WHERE npm = '"+tfNPM.getText()+"'";
            st.executeUpdate(SQL);
            isitabel();
            clear();
            JOptionPane.showMessageDialog(null, "berhasil hapus");
           
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_bthapusActionPerformed

    private void btBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBersihkanActionPerformed
        clear();        // TODO add your handling code here:
    }//GEN-LAST:event_btBersihkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Halaman_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Halaman_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Halaman_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Halaman_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Halaman_Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFNAMA;
    private javax.swing.JTextField TFROLE;
    private javax.swing.JTextField TFSEMESTER;
    private javax.swing.JTextField TFTAHUN;
    private javax.swing.JButton btBersihkan;
    private javax.swing.JButton btUBAH;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton bttambah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_mhs;
    private javax.swing.JTextField tfNPM;
    // End of variables declaration//GEN-END:variables
}
