/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javafx.scene.input.Mnemonic;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import  koneksi.koneksi;

/**
 *
 * 
 */

public class Halaman_Matakuliah extends javax.swing.JFrame {
private DefaultTableModel model;
 

public void  matakuliah(){
model = new DefaultTableModel ();
             tabel_matakuliah.setModel(model);
             model.addColumn("ID");
             model.addColumn("Nama MataKuliah");             
             model.addColumn("Semester");
             model.addColumn("Sks");
             model.addColumn("Fakultas");
             model.addColumn("Jurusan");
             
             isitabel();
}


public void isitabel( ){
    
     model.getDataVector( ).removeAllElements( );
     model.fireTableDataChanged( );

     try{
          
           Statement st = (Statement) koneksi.konn(). createStatement( );
           String sql   = "Select * from matakuliah";
           ResultSet res   = st.executeQuery(sql);

           
           while(res.next ()){
                Object[ ] obj = new Object[6];
                obj[0] = res.getString("id_matakuliah");
                obj[1] = res.getString("nama");
                obj[2] = res.getString("semester");
                obj[3] = res.getString("sks");
                obj[4] = res.getString("fakultas");
                obj[5] = res.getString("jurusan");
                

                model.addRow(obj);
            }
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }
}





    public Halaman_Matakuliah() {
        initComponents();
        matakuliah();
        
        
             
    }
    

     public void clear(){
TFNAMA.setText("");
tfidmatakuliah.setText("");
TFSEMESTER.setText("");
TFfakultas.setText("");
TFsks.setText("");
TFjurusan.setText("");

}
            
 
             
             
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfidmatakuliah = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFNAMA = new javax.swing.JTextField();
        TFsks = new javax.swing.JTextField();
        TFSEMESTER = new javax.swing.JTextField();
        TFfakultas = new javax.swing.JTextField();
        bttambah = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btUBAH = new javax.swing.JButton();
        btBersihkan = new javax.swing.JButton();
        TFjurusan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_matakuliah = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        tfidmatakuliah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfidmatakuliah.setForeground(new java.awt.Color(0, 0, 0));
        tfidmatakuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidmatakuliahActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NAMA");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("SKS");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("FAKULTAS");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("SEMESTER");

        TFNAMA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TFNAMA.setForeground(new java.awt.Color(0, 0, 0));
        TFNAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNAMAActionPerformed(evt);
            }
        });

        TFsks.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TFsks.setForeground(new java.awt.Color(0, 0, 0));
        TFsks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFsksActionPerformed(evt);
            }
        });

        TFSEMESTER.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TFSEMESTER.setForeground(new java.awt.Color(0, 0, 0));
        TFSEMESTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSEMESTERActionPerformed(evt);
            }
        });

        TFfakultas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TFfakultas.setForeground(new java.awt.Color(0, 0, 0));
        TFfakultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFfakultasActionPerformed(evt);
            }
        });

        bttambah.setBackground(new java.awt.Color(102, 255, 51));
        bttambah.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        bttambah.setForeground(new java.awt.Color(0, 0, 0));
        bttambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_save_35px_4.png"))); // NOI18N
        bttambah.setText("ADD");
        bttambah.setBorder(null);
        bttambah.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });

        bthapus.setBackground(new java.awt.Color(255, 0, 51));
        bthapus.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        bthapus.setForeground(new java.awt.Color(0, 0, 0));
        bthapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_delete_35px.png"))); // NOI18N
        bthapus.setText("DELETE");
        bthapus.setBorder(null);
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        btUBAH.setBackground(new java.awt.Color(255, 153, 51));
        btUBAH.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btUBAH.setForeground(new java.awt.Color(0, 0, 0));
        btUBAH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_edit_file_35px.png"))); // NOI18N
        btUBAH.setText("EDIT");
        btUBAH.setBorder(null);
        btUBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUBAHActionPerformed(evt);
            }
        });

        btBersihkan.setBackground(new java.awt.Color(255, 255, 255));
        btBersihkan.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btBersihkan.setForeground(new java.awt.Color(0, 0, 0));
        btBersihkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_eraser_35px.png"))); // NOI18N
        btBersihkan.setText("CLEAR");
        btBersihkan.setBorder(null);
        btBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBersihkanActionPerformed(evt);
            }
        });

        TFjurusan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TFjurusan.setForeground(new java.awt.Color(0, 0, 0));
        TFjurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFjurusanActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Jurusan");

        tabel_matakuliah.setBackground(new java.awt.Color(255, 255, 255));
        tabel_matakuliah.setForeground(new java.awt.Color(51, 51, 51));
        tabel_matakuliah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_matakuliah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_matakuliahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_matakuliah);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFfakultas, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFsks, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfidmatakuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TFSEMESTER, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttambah, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btUBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfidmatakuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TFNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFsks, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TFfakultas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btUBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bttambah, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFSEMESTER, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(95, 95, 95)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_close_window_35px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MATAKULIAH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(329, 329, 329)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfidmatakuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidmatakuliahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfidmatakuliahActionPerformed

    private void TFNAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNAMAActionPerformed

    private void TFsksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFsksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFsksActionPerformed

    private void TFSEMESTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSEMESTERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFSEMESTERActionPerformed

    private void TFfakultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFfakultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFfakultasActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
       try {
           if(tfidmatakuliah.getText().equals("")){
            JOptionPane.showMessageDialog(null, " TIDAK BOLEH KOSONG");
        } else if (TFNAMA.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }
        else if (TFsks.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }else if (TFjurusan.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }else if (TFSEMESTER.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }else if (TFfakultas.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }
        else {
            String sql = "INSERT INTO matakuliah VALUES ('"+tfidmatakuliah.getText()+"','"+TFNAMA.getText()+"','"+TFsks.getText()+"','"+TFSEMESTER.getText()+"','"+TFfakultas.getText()+"','"+TFjurusan.getText()+"')";
            java.sql.Connection conn=(Connection)koneksi.konn();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan");
            isitabel();
            clear();
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_bttambahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btUBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUBAHActionPerformed
try{
            koneksi.konn();
             Statement st = (Statement) koneksi.konn(). createStatement( );
            String SQL = "update matakuliah SET id_matakuliah = '"+tfidmatakuliah.getText()+"', nama = '"+TFNAMA.getText()+"', sks = '"
             +TFsks.getText()+"', semester = '"+TFSEMESTER.getText()+"', fakultas = '"+TFfakultas.getText()+"', jurusan = '"+TFjurusan.getText()+"' WHERE id_matakuliah= '"+tfidmatakuliah.getText()+"'";
            st.executeUpdate(SQL);
            isitabel();
             clear();
            JOptionPane.showMessageDialog(null, " Data berhasil edit");
           
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }        
    }//GEN-LAST:event_btUBAHActionPerformed

    private void tabel_matakuliahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_matakuliahMouseClicked
try {
            koneksi.konn();
            int row =tabel_matakuliah.getSelectedRow();
            String tabel_klik=(tabel_matakuliah.getModel().getValueAt(row, 0).toString());
            java.sql.Statement stm = koneksi.konn() .createStatement();
            java.sql.ResultSet sql = stm.executeQuery("select * from matakuliah where id_matakuliah='"+tabel_klik+"'");
            if(sql.next()){
                String id = sql.getString("id_matakuliah");
                tfidmatakuliah.setText(id);
                String nama = sql.getString("nama");
                TFNAMA.setText(nama);
                 String semester = sql.getString("semester");
                TFSEMESTER.setText(semester);
                String sks = sql.getString("sks");
                TFsks.setText(sks);               
                String fakultas = sql.getString("fakultas");
                TFfakultas.setText(fakultas);
                String jurusan = sql.getString("jurusan");
                TFjurusan.setText(jurusan);
            }
        } catch (Exception e) {}       
    }//GEN-LAST:event_tabel_matakuliahMouseClicked

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
       try{
           koneksi.konn();
          Statement  st = koneksi.konn().createStatement();
            String SQL = "DELETE FROM matakuliah WHERE id_matakuliah = '"+tfidmatakuliah.getText()+"'";
            st.executeUpdate(SQL);
            isitabel();
            clear();
            JOptionPane.showMessageDialog(null, "berhasil hapus");
           
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_bthapusActionPerformed

    private void btBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBersihkanActionPerformed
        clear();        // TODO add your handling code here:
    }//GEN-LAST:event_btBersihkanActionPerformed

    private void TFjurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFjurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFjurusanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Halaman_Matakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Halaman_Matakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Halaman_Matakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Halaman_Matakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Halaman_Matakuliah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFNAMA;
    private javax.swing.JTextField TFSEMESTER;
    private javax.swing.JTextField TFfakultas;
    private javax.swing.JTextField TFjurusan;
    private javax.swing.JTextField TFsks;
    private javax.swing.JButton btBersihkan;
    private javax.swing.JButton btUBAH;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton bttambah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_matakuliah;
    private javax.swing.JTextField tfidmatakuliah;
    // End of variables declaration//GEN-END:variables
}
