/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javafx.scene.input.Mnemonic;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import  koneksi.koneksi;

/**
 *
 * 
 */

public class Halaman_Transaksi extends javax.swing.JFrame {
private DefaultTableModel model;
 

public void  Transaksi(){
model = new DefaultTableModel ();
             tabel_transaksi.setModel(model);
             model.addColumn("ID Transaksi");
            
             model.addColumn("Npm");
             model.addColumn("Biaya");
             model.addColumn("Pajak %");
             model.addColumn("Total");
             
             
             isitabel();
}
public void kombobox (){
try {
             String sql = "Select *from mahasiswa";
            java.sql.Statement stat = koneksi.konn().createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            
            while (hasil.next()){
             kbbkNPM.addItem(hasil.getString("npm"));
             
            }
            
        } catch (Exception e) {
        }}


public void isitabel( ){
    
     model.getDataVector( ).removeAllElements( );
     model.fireTableDataChanged( );

     try{
          
           Statement st = (Statement) koneksi.konn(). createStatement( );
           String sql   = "Select * from transaksi";
           ResultSet res   = st.executeQuery(sql);

           
           while(res.next ()){
                Object[ ] obj = new Object[5];
                obj[0] = res.getString("id_transaksi");                
                obj[1] = res.getString("npm");
                obj[2] = res.getString("biaya");
                obj[3] = res.getString("pajak");
                obj[4] = res.getString("total_keseluruhan");
                             

                model.addRow(obj);
            }
           
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }
     
}





    public Halaman_Transaksi() {
        initComponents();
        Transaksi();
        kombobox();
        
        
             
    }
    
public void clear(){
tfnama.setText("");
tfidTransaksi.setText("");

TFPajak.setText("");
TFTotal.setText("");
TFbiaya.setText("");

kbbkNPM.setSelectedIndex(0);

}
     
            
 
             
             
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfidTransaksi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFbiaya = new javax.swing.JTextField();
        TFTotal = new javax.swing.JTextField();
        bttambah = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btUBAH = new javax.swing.JButton();
        btBersihkan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_transaksi = new javax.swing.JTable();
        kbbkNPM = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TFPajak = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        tfnama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        tfidTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfidTransaksi.setForeground(new java.awt.Color(0, 0, 0));
        tfidTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidTransaksiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID Transaksi");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NPM");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Biaya");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Total");

        TFbiaya.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TFbiaya.setForeground(new java.awt.Color(0, 0, 0));
        TFbiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFbiayaActionPerformed(evt);
            }
        });
        TFbiaya.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFbiayaKeyTyped(evt);
            }
        });

        TFTotal.setEditable(false);
        TFTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TFTotal.setForeground(new java.awt.Color(0, 0, 0));
        TFTotal.setFocusable(false);
        TFTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTotalActionPerformed(evt);
            }
        });

        bttambah.setBackground(new java.awt.Color(102, 255, 51));
        bttambah.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        bttambah.setForeground(new java.awt.Color(0, 0, 0));
        bttambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_save_35px_4.png"))); // NOI18N
        bttambah.setText("ADD");
        bttambah.setBorder(null);
        bttambah.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });

        bthapus.setBackground(new java.awt.Color(255, 0, 51));
        bthapus.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        bthapus.setForeground(new java.awt.Color(0, 0, 0));
        bthapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_delete_35px.png"))); // NOI18N
        bthapus.setText("DELETE");
        bthapus.setBorder(null);
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        btUBAH.setBackground(new java.awt.Color(255, 153, 51));
        btUBAH.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btUBAH.setForeground(new java.awt.Color(0, 0, 0));
        btUBAH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_edit_file_35px.png"))); // NOI18N
        btUBAH.setText("EDIT");
        btUBAH.setBorder(null);
        btUBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUBAHActionPerformed(evt);
            }
        });

        btBersihkan.setBackground(new java.awt.Color(255, 255, 255));
        btBersihkan.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btBersihkan.setForeground(new java.awt.Color(0, 0, 0));
        btBersihkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_eraser_35px.png"))); // NOI18N
        btBersihkan.setText("CLEAR");
        btBersihkan.setBorder(null);
        btBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBersihkanActionPerformed(evt);
            }
        });

        tabel_transaksi.setBackground(new java.awt.Color(255, 255, 255));
        tabel_transaksi.setForeground(new java.awt.Color(51, 51, 51));
        tabel_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_transaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_transaksi);

        kbbkNPM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih NPM" }));
        kbbkNPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbbkNPMActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nama");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Pajak");

        TFPajak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TFPajak.setForeground(new java.awt.Color(0, 0, 0));
        TFPajak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFPajakActionPerformed(evt);
            }
        });
        TFPajak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFPajakKeyTyped(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 204, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_calculator_35px_1.png"))); // NOI18N
        jButton2.setText("HITUNG");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tfnama.setEditable(false);
        tfnama.setFocusable(false);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel9)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(tfidTransaksi)
                    .addComponent(kbbkNPM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFTotal)
                    .addComponent(TFbiaya)
                    .addComponent(tfnama, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TFPajak, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)))
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttambah, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btUBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfidTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(kbbkNPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFbiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFPajak, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btUBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bttambah, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)))
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(76, 76, 76)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_close_window_35px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("INPUT TRANSAKSI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(239, 239, 239)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfidTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfidTransaksiActionPerformed

    private void TFbiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFbiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFbiayaActionPerformed

    private void TFTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTotalActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
       try {
           if(tfidTransaksi.getText().equals("")){
            JOptionPane.showMessageDialog(null, " TIDAK BOLEH KOSONG");
        } else if (kbbkNPM.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }else if (TFPajak.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }
        else if (TFbiaya.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }else if (TFTotal.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }
        else {
            String sql = "INSERT INTO transaksi VALUES ('"+tfidTransaksi.getText()+"','"+kbbkNPM.getSelectedItem()+"','"+TFbiaya.getText()+"','"+TFPajak.getText()+"','"+TFTotal.getText()+"')";
            java.sql.Connection conn=(Connection)koneksi.konn();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan");
            isitabel();
            clear();
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_bttambahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btUBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUBAHActionPerformed

   try {
           if(tfidTransaksi.getText().equals("")){
            JOptionPane.showMessageDialog(null, " TIDAK BOLEH KOSONG");
        } else if (kbbkNPM.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }else if (TFPajak.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }
        else if (TFbiaya.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }else if (TFTotal.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }
        else {
            koneksi.konn();
             Statement st = (Statement) koneksi.konn(). createStatement( );
            String SQL = "update transaksi SET id_transaksi = '"+tfidTransaksi.getText()+"', pajak = '"+TFPajak.getText()+"', npm = '"+kbbkNPM.getSelectedItem()+"', biaya = '"
             +TFbiaya.getText()+"',total_keseluruhan = '"+TFTotal.getText()+"' WHERE id_transaksi= '"+tfidTransaksi.getText()+"'";
            st.executeUpdate(SQL);
            isitabel();
             clear();
            JOptionPane.showMessageDialog(null, " Data berhasil edit");
        }
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }        
    }//GEN-LAST:event_btUBAHActionPerformed

    private void tabel_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_transaksiMouseClicked
try {
            koneksi.konn();
            int row =tabel_transaksi.getSelectedRow();
            String tabel_klik=(tabel_transaksi.getModel().getValueAt(row, 0).toString());
            java.sql.Statement stm = koneksi.konn() .createStatement();
            java.sql.ResultSet sql = stm.executeQuery("select * from transaksi where id_transaksi='"+tabel_klik+"'");
            if(sql.next()){
                String id = sql.getString("id_transaksi");
                tfidTransaksi.setText(id);
                String npm = sql.getString("npm");
                kbbkNPM.setSelectedItem(npm);
               
                 String pajak = sql.getString("pajak");
                TFPajak.setText(pajak);
                String biaya = sql.getString("biaya");
                TFbiaya.setText(biaya);               
                String total = sql.getString("total_keseluruhan");
                TFTotal.setText(total);
                
            }
        } catch (Exception e) {}       
    }//GEN-LAST:event_tabel_transaksiMouseClicked

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
       try{
           koneksi.konn();
          Statement  st = koneksi.konn().createStatement();
            String SQL = "DELETE FROM transaksi WHERE id_transaksi = '"+tfidTransaksi.getText()+"'";
            st.executeUpdate(SQL);
            isitabel();
            clear();
            JOptionPane.showMessageDialog(null, "berhasil hapus");
           
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_bthapusActionPerformed

    private void btBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBersihkanActionPerformed
        clear();        // TODO add your handling code here:
    }//GEN-LAST:event_btBersihkanActionPerformed

    private void kbbkNPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbbkNPMActionPerformed
 try {
            String sql="select * from mahasiswa where npm='"+kbbkNPM.getSelectedItem()+"'";
             java.sql.Statement stat = koneksi.konn().createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {                
                tfnama.setText(hasil.getString("nama"));
            }
        } catch (Exception e) {
        }     
    }//GEN-LAST:event_kbbkNPMActionPerformed

    private void TFPajakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFPajakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFPajakActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      double a,b,c,d,e;
      
      a=Double.parseDouble(TFbiaya.getText());
      b=Double.parseDouble(TFPajak.getText());
      
      c=b/100*a;
      d=c+a;
      TFTotal.setText(Double.toString(d));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TFPajakKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFPajakKeyTyped
char c= evt.getKeyChar();
        if(! ((Character.isDigit(c)) ||
            ( c== KeyEvent.VK_BACK_SPACE)
            || (c== KeyEvent.VK_DELETE)
        ))
        {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Hanya angka 1-9");
            TFPajak.requestFocus();
            evt.consume();
        }       
    }//GEN-LAST:event_TFPajakKeyTyped

    private void TFbiayaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFbiayaKeyTyped
      char c= evt.getKeyChar();
        if(! ((Character.isDigit(c)) ||
            ( c== KeyEvent.VK_BACK_SPACE)
            || (c== KeyEvent.VK_DELETE)
        ))
        {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Hanya angka 1-9");
            TFbiaya.requestFocus();
            evt.consume();
        }  
    }//GEN-LAST:event_TFbiayaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Halaman_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Halaman_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Halaman_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Halaman_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Halaman_Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFPajak;
    private javax.swing.JTextField TFTotal;
    private javax.swing.JTextField TFbiaya;
    private javax.swing.JButton btBersihkan;
    private javax.swing.JButton btUBAH;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton bttambah;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kbbkNPM;
    private javax.swing.JTable tabel_transaksi;
    private javax.swing.JTextField tfidTransaksi;
    private javax.swing.JTextField tfnama;
    // End of variables declaration//GEN-END:variables
}
