/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javafx.scene.input.Mnemonic;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import  koneksi.koneksi;

/**
 *
 * 
 */

public class Halaman_KRS extends javax.swing.JFrame {
private DefaultTableModel model;
 

public void  KRS(){
model = new DefaultTableModel ();
             tabel_KRS.setModel(model);
             model.addColumn("ID Krs");
             model.addColumn("ID MATAKULIAH");             
             model.addColumn("Dosen");
             model.addColumn("Kelas");
             model.addColumn("Semester");
             model.addColumn("Jam");
             model.addColumn("Hari");
             
             isitabel();
}
public void kombobox (){
try {
             String sql = "select * from matakuliah";
            java.sql.Statement stat = koneksi.konn().createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            
            while (hasil.next()){
             kbbkIdMatkul.addItem(hasil.getString("id_matakuliah"));
             
            }
            
        } catch (Exception e) {
        }}


public void isitabel( ){
    
     model.getDataVector( ).removeAllElements( );
     model.fireTableDataChanged( );

     try{
          
           Statement st = (Statement) koneksi.konn(). createStatement( );
           String sql   = "Select * from krs";
           ResultSet res   = st.executeQuery(sql);

           
           while(res.next ()){
                Object[ ] obj = new Object[7];
                obj[0] = res.getString("id_krs");
                obj[1] = res.getString("id_matakuliah");
                obj[2] = res.getString("dosen");
                obj[3] = res.getString("kelas");
                obj[4] = res.getString("semester");
                obj[5] = res.getString("jam");
                obj[6] = res.getString("hari");              

                model.addRow(obj);
            }
           
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }
     
}





    public Halaman_KRS() {
        initComponents();
        KRS();
        kombobox();
        
        
             
    }
    
public void clear(){
TFnamamatkul.setText("");
tfidkrs.setText("");
TFHari.setText("");
TFsemester.setText("");
TFKelas.setText("");
TFdosen.setText("");
TfJam.setText("");
kbbkIdMatkul.setSelectedIndex(0);

}
     
            
 
             
             
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfidkrs = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFdosen = new javax.swing.JTextField();
        TFHari = new javax.swing.JTextField();
        TFKelas = new javax.swing.JTextField();
        bttambah = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btUBAH = new javax.swing.JButton();
        btBersihkan = new javax.swing.JButton();
        TfJam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_KRS = new javax.swing.JTable();
        kbbkIdMatkul = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        TFnamamatkul = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TFsemester = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        tfidkrs.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfidkrs.setForeground(new java.awt.Color(0, 0, 0));
        tfidkrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidkrsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID KRS");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID MATAKLUIAH");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama Dosen");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Kelas");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Hari");

        TFdosen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TFdosen.setForeground(new java.awt.Color(0, 0, 0));
        TFdosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFdosenActionPerformed(evt);
            }
        });

        TFHari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TFHari.setForeground(new java.awt.Color(0, 0, 0));
        TFHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFHariActionPerformed(evt);
            }
        });

        TFKelas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TFKelas.setForeground(new java.awt.Color(0, 0, 0));
        TFKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFKelasActionPerformed(evt);
            }
        });

        bttambah.setBackground(new java.awt.Color(102, 255, 51));
        bttambah.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        bttambah.setForeground(new java.awt.Color(0, 0, 0));
        bttambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_save_35px_4.png"))); // NOI18N
        bttambah.setText("ADD");
        bttambah.setBorder(null);
        bttambah.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });

        bthapus.setBackground(new java.awt.Color(255, 0, 51));
        bthapus.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        bthapus.setForeground(new java.awt.Color(0, 0, 0));
        bthapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_delete_35px.png"))); // NOI18N
        bthapus.setText("DELETE");
        bthapus.setBorder(null);
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        btUBAH.setBackground(new java.awt.Color(255, 153, 51));
        btUBAH.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btUBAH.setForeground(new java.awt.Color(0, 0, 0));
        btUBAH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_edit_file_35px.png"))); // NOI18N
        btUBAH.setText("EDIT");
        btUBAH.setBorder(null);
        btUBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUBAHActionPerformed(evt);
            }
        });

        btBersihkan.setBackground(new java.awt.Color(255, 255, 255));
        btBersihkan.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btBersihkan.setForeground(new java.awt.Color(0, 0, 0));
        btBersihkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_eraser_35px.png"))); // NOI18N
        btBersihkan.setText("CLEAR");
        btBersihkan.setBorder(null);
        btBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBersihkanActionPerformed(evt);
            }
        });

        TfJam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TfJam.setForeground(new java.awt.Color(0, 0, 0));
        TfJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfJamActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Jam");

        tabel_KRS.setBackground(new java.awt.Color(255, 255, 255));
        tabel_KRS.setForeground(new java.awt.Color(51, 51, 51));
        tabel_KRS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_KRS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_KRSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_KRS);

        kbbkIdMatkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih ID Mata Kuliah" }));
        kbbkIdMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbbkIdMatkulActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nama Matakuliah");

        TFnamamatkul.setEditable(false);
        TFnamamatkul.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TFnamamatkul.setForeground(new java.awt.Color(0, 0, 0));
        TFnamamatkul.setFocusable(false);
        TFnamamatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnamamatkulActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Semester");

        TFsemester.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TFsemester.setForeground(new java.awt.Color(0, 0, 0));
        TFsemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFsemesterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFsemester)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfidkrs, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addComponent(kbbkIdMatkul, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TFnamamatkul))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TFKelas)
                        .addComponent(TFdosen)
                        .addComponent(TfJam, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                    .addComponent(TFHari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttambah, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btUBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btUBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bttambah, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfidkrs, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(kbbkIdMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TFnamamatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFdosen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFsemester, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TfJam, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFHari, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_close_window_35px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("INPUT KRS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(329, 329, 329)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfidkrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidkrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfidkrsActionPerformed

    private void TFdosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFdosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFdosenActionPerformed

    private void TFHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFHariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFHariActionPerformed

    private void TFKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFKelasActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
       try {
           if(tfidkrs.getText().equals("")){
            JOptionPane.showMessageDialog(null, " TIDAK BOLEH KOSONG");
        } else if (kbbkIdMatkul.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }else if (TFsemester.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }
        else if (TFdosen.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }else if (TfJam.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }else if (TFHari.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }else if (TFKelas.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }
        else {
            String sql = "INSERT INTO krs VALUES ('"+tfidkrs.getText()+"','"+kbbkIdMatkul.getSelectedItem()+"','"+TFdosen.getText()+"','"+TFKelas.getText()+"','"+TFsemester.getText()+"','"+TfJam.getText()+"','"+TFHari.getText()+"')";
            java.sql.Connection conn=(Connection)koneksi.konn();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan");
            isitabel();
            clear();
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_bttambahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btUBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUBAHActionPerformed
try{
    if(tfidkrs.getText().equals("")){
            JOptionPane.showMessageDialog(null, " TIDAK BOLEH KOSONG");
        } else if (kbbkIdMatkul.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }else if (TFsemester.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }
        else if (TFdosen.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }else if (TfJam.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }else if (TFHari.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }else if (TFKelas.getText().equals("")){
            JOptionPane.showMessageDialog(null, "  tidak boleh kosong");
        }
        else {
            koneksi.konn();
             Statement st = (Statement) koneksi.konn(). createStatement( );
            String SQL = "update krs SET id_krs = '"+tfidkrs.getText()+"', semester = '"+TFsemester.getText()+"', id_matakuliah = '"+kbbkIdMatkul.getSelectedItem()+"', dosen = '"
             +TFdosen.getText()+"', hari = '"+TFHari.getText()+"', kelas = '"+TFKelas.getText()+"', jam = '"+TfJam.getText()+"' WHERE id_krs= '"+tfidkrs.getText()+"'";
            st.executeUpdate(SQL);
            isitabel();
             clear();
            JOptionPane.showMessageDialog(null, " Data berhasil edit");
        }
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }        
    }//GEN-LAST:event_btUBAHActionPerformed

    private void tabel_KRSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_KRSMouseClicked
try {
            koneksi.konn();
            int row =tabel_KRS.getSelectedRow();
            String tabel_klik=(tabel_KRS.getModel().getValueAt(row, 0).toString());
            java.sql.Statement stm = koneksi.konn() .createStatement();
            java.sql.ResultSet sql = stm.executeQuery("select * from krs where id_krs='"+tabel_klik+"'");
            if(sql.next()){
                String id = sql.getString("id_krs");
                tfidkrs.setText(id);
                String id_matkul = sql.getString("id_matakuliah");
                kbbkIdMatkul.setSelectedItem(id_matkul);
                String hari = sql.getString("hari");
                TFHari.setText(hari);
                 String semester = sql.getString("semester");
                TFsemester.setText(semester);
                String dosen = sql.getString("dosen");
                TFdosen.setText(dosen);               
                String kelas = sql.getString("kelas");
                TFKelas.setText(kelas);
                String jam = sql.getString("jam");
                TfJam.setText(jam);
            }
        } catch (Exception e) {}       
    }//GEN-LAST:event_tabel_KRSMouseClicked

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
       try{
           koneksi.konn();
          Statement  st = koneksi.konn().createStatement();
            String SQL = "DELETE FROM krs WHERE id_krs = '"+tfidkrs.getText()+"'";
            st.executeUpdate(SQL);
            isitabel();
            clear();
            JOptionPane.showMessageDialog(null, "berhasil hapus");
           
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_bthapusActionPerformed

    private void btBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBersihkanActionPerformed
        clear();        // TODO add your handling code here:
    }//GEN-LAST:event_btBersihkanActionPerformed

    private void TfJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfJamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfJamActionPerformed

    private void TFnamamatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnamamatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnamamatkulActionPerformed

    private void kbbkIdMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbbkIdMatkulActionPerformed
 try {
            String sql="select * from matakuliah where id_matakuliah='"+kbbkIdMatkul.getSelectedItem()+"'";
             java.sql.Statement stat = koneksi.konn().createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {                
                TFnamamatkul.setText(hasil.getString("nama"));
            }
        } catch (Exception e) {
        }     
    }//GEN-LAST:event_kbbkIdMatkulActionPerformed

    private void TFsemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFsemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFsemesterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Halaman_KRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Halaman_KRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Halaman_KRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Halaman_KRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Halaman_KRS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFHari;
    private javax.swing.JTextField TFKelas;
    private javax.swing.JTextField TFdosen;
    private javax.swing.JTextField TFnamamatkul;
    private javax.swing.JTextField TFsemester;
    private javax.swing.JTextField TfJam;
    private javax.swing.JButton btBersihkan;
    private javax.swing.JButton btUBAH;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton bttambah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kbbkIdMatkul;
    private javax.swing.JTable tabel_KRS;
    private javax.swing.JTextField tfidkrs;
    // End of variables declaration//GEN-END:variables
}
