/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import java.awt.Color;
import javax.swing.JOptionPane;


public class MenuUtama extends javax.swing.JFrame {
 
//    public void style(){
//    
//    }
//    public void styleawal(){
//    btnmhs1.setBackground(new Color(187,187,187));
//   
//
//    }
//    
    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel = new javax.swing.JPanel();
        DrawerPanel = new javax.swing.JPanel();
        SubDataMenupnl = new javax.swing.JPanel();
        btnmhs1 = new javax.swing.JButton();
        btnmatakuliah = new javax.swing.JButton();
        btndata = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnMenuInput = new javax.swing.JButton();
        SubInputMenuPnl = new javax.swing.JPanel();
        btnKrs = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnTransaksi = new javax.swing.JButton();
        SubLaporanMenupnl2 = new javax.swing.JPanel();
        btnLaporann = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnMenuIaporan = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        MenuPanel.setBackground(new java.awt.Color(51, 51, 51));
        MenuPanel.setForeground(new java.awt.Color(255, 255, 255));

        DrawerPanel.setBackground(new java.awt.Color(187, 187, 187));

        SubDataMenupnl.setBackground(new java.awt.Color(153, 153, 153));

        btnmhs1.setBackground(new java.awt.Color(187, 187, 187));
        btnmhs1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnmhs1.setForeground(new java.awt.Color(102, 102, 102));
        btnmhs1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Plus_35px.png"))); // NOI18N
        btnmhs1.setText("Mahasiswa");
        btnmhs1.setBorder(null);
        btnmhs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmhs1ActionPerformed(evt);
            }
        });

        btnmatakuliah.setBackground(new java.awt.Color(187, 187, 187));
        btnmatakuliah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnmatakuliah.setForeground(new java.awt.Color(102, 102, 102));
        btnmatakuliah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Plus_35px.png"))); // NOI18N
        btnmatakuliah.setText("Matakuliah");
        btnmatakuliah.setBorder(null);
        btnmatakuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmatakuliahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SubDataMenupnlLayout = new javax.swing.GroupLayout(SubDataMenupnl);
        SubDataMenupnl.setLayout(SubDataMenupnlLayout);
        SubDataMenupnlLayout.setHorizontalGroup(
            SubDataMenupnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubDataMenupnlLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(SubDataMenupnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmhs1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmatakuliah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        SubDataMenupnlLayout.setVerticalGroup(
            SubDataMenupnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubDataMenupnlLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnmhs1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmatakuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btndata.setBackground(new java.awt.Color(102, 102, 102));
        btndata.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndata.setForeground(new java.awt.Color(255, 255, 255));
        btndata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_shop_35px_1.png"))); // NOI18N
        btndata.setText("DATA     ");
        btndata.setBorder(null);
        btndata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndataActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(187, 187, 187));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_name_100px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("ADMIN");

        btnMenuInput.setBackground(new java.awt.Color(102, 102, 102));
        btnMenuInput.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenuInput.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_linux_client_35px.png"))); // NOI18N
        btnMenuInput.setText("INPUT      ");
        btnMenuInput.setBorder(null);
        btnMenuInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuInputActionPerformed(evt);
            }
        });

        SubInputMenuPnl.setBackground(new java.awt.Color(153, 153, 153));

        btnKrs.setBackground(new java.awt.Color(187, 187, 187));
        btnKrs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKrs.setForeground(new java.awt.Color(102, 102, 102));
        btnKrs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_purchase_order_35px_1.png"))); // NOI18N
        btnKrs.setText("KRS         ");
        btnKrs.setBorder(null);
        btnKrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKrsActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnTransaksi.setBackground(new java.awt.Color(187, 187, 187));
        btnTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTransaksi.setForeground(new java.awt.Color(102, 102, 102));
        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Initiate_Money_Transfer_35px.png"))); // NOI18N
        btnTransaksi.setText("Transaksi");
        btnTransaksi.setBorder(null);
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SubInputMenuPnlLayout = new javax.swing.GroupLayout(SubInputMenuPnl);
        SubInputMenuPnl.setLayout(SubInputMenuPnlLayout);
        SubInputMenuPnlLayout.setHorizontalGroup(
            SubInputMenuPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubInputMenuPnlLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(SubInputMenuPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SubInputMenuPnlLayout.setVerticalGroup(
            SubInputMenuPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubInputMenuPnlLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(SubInputMenuPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SubInputMenuPnlLayout.createSequentialGroup()
                        .addComponent(btnKrs, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        SubLaporanMenupnl2.setBackground(new java.awt.Color(153, 153, 153));

        btnLaporann.setBackground(new java.awt.Color(187, 187, 187));
        btnLaporann.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLaporann.setForeground(new java.awt.Color(102, 102, 102));
        btnLaporann.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_working_with_a_laptop_35px.png"))); // NOI18N
        btnLaporann.setText("TRANSAKSI");
        btnLaporann.setBorder(null);
        btnLaporann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporannActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout SubLaporanMenupnl2Layout = new javax.swing.GroupLayout(SubLaporanMenupnl2);
        SubLaporanMenupnl2.setLayout(SubLaporanMenupnl2Layout);
        SubLaporanMenupnl2Layout.setHorizontalGroup(
            SubLaporanMenupnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubLaporanMenupnl2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLaporann, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        SubLaporanMenupnl2Layout.setVerticalGroup(
            SubLaporanMenupnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubLaporanMenupnl2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(SubLaporanMenupnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SubLaporanMenupnl2Layout.createSequentialGroup()
                        .addComponent(btnLaporann, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        btnMenuIaporan.setBackground(new java.awt.Color(102, 102, 102));
        btnMenuIaporan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenuIaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuIaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_business_report_35px.png"))); // NOI18N
        btnMenuIaporan.setText("LAPORAN");
        btnMenuIaporan.setBorder(null);
        btnMenuIaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuIaporanActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DrawerPanelLayout = new javax.swing.GroupLayout(DrawerPanel);
        DrawerPanel.setLayout(DrawerPanelLayout);
        DrawerPanelLayout.setHorizontalGroup(
            DrawerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrawerPanelLayout.createSequentialGroup()
                .addGroup(DrawerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndata, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubDataMenupnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DrawerPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton1))
                    .addGroup(DrawerPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1))
                    .addComponent(SubLaporanMenupnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DrawerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnMenuInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SubInputMenuPnl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnMenuIaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
            .addGroup(DrawerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DrawerPanelLayout.createSequentialGroup()
                    .addGap(98, 98, 98)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(98, Short.MAX_VALUE)))
        );
        DrawerPanelLayout.setVerticalGroup(
            DrawerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrawerPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(100, 100, 100)
                .addComponent(btndata, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SubDataMenupnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnMenuInput, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SubInputMenuPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnMenuIaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SubLaporanMenupnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(DrawerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DrawerPanelLayout.createSequentialGroup()
                    .addGap(299, 299, 299)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(299, 299, 299)))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("APLIKASI PENGELOLAAN KRS");

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_shutdown_40px.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addComponent(DrawerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 480, Short.MAX_VALUE)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(490, 490, 490))))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DrawerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(254, 254, 254)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     setExtendedState(MenuUtama.MAXIMIZED_BOTH);
        SubDataMenupnl.setVisible(false);
        SubInputMenuPnl.setVisible(false);
       SubLaporanMenupnl2.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btndataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndataActionPerformed
        SubDataMenupnl.setVisible(true);
         SubInputMenuPnl.setVisible(false);
       SubLaporanMenupnl2.setVisible(false);
    }//GEN-LAST:event_btndataActionPerformed

    private void btnmhs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmhs1ActionPerformed
     new Halaman_Mahasiswa().setVisible(true);
    }//GEN-LAST:event_btnmhs1ActionPerformed

    private void btnmatakuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmatakuliahActionPerformed
        new Halaman_Matakuliah().setVisible(true);
    }//GEN-LAST:event_btnmatakuliahActionPerformed

    private void btnMenuInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuInputActionPerformed
        SubInputMenuPnl.setVisible(true);  
 
        SubDataMenupnl.setVisible(false);
       SubLaporanMenupnl2.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnMenuInputActionPerformed

    private void btnKrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKrsActionPerformed
     new Halaman_KRS().setVisible(true);
    }//GEN-LAST:event_btnKrsActionPerformed

    private void btnMenuIaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuIaporanActionPerformed
SubInputMenuPnl.setVisible(false);  
 
        SubDataMenupnl.setVisible(false);
       SubLaporanMenupnl2.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuIaporanActionPerformed

    private void btnLaporannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporannActionPerformed
        new Halaman_Laporan().setVisible(true );
    }//GEN-LAST:event_btnLaporannActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        new Halaman_Transaksi().setVisible(true);
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new Halaman_admin().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 int confirm=  JOptionPane.showConfirmDialog(this, "Apakah Yakin ingin Log Out","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (confirm== JOptionPane.YES_OPTION) {
            System.exit(0);
            
        }  
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DrawerPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel SubDataMenupnl;
    private javax.swing.JPanel SubInputMenuPnl;
    private javax.swing.JPanel SubLaporanMenupnl2;
    private javax.swing.JButton btnKrs;
    private javax.swing.JButton btnLaporann;
    private javax.swing.JButton btnMenuIaporan;
    private javax.swing.JButton btnMenuInput;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton btndata;
    private javax.swing.JButton btnmatakuliah;
    public javax.swing.JButton btnmhs1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
